version: "2"
services:
  shop:
    build: ./shop
    links:
      - db
      - react
      - prometheus
    ports:
      - "5000:5000"
  db:
    build: ./db
    ports:
      - "32000:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  react:
    build: ./layout
    ports:
      - "3001:3000"
  prometheus:
    image: prom/prometheus:v2.2.1
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
