global:
  scrape_interval: 20s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "shop"
    scheme: https
    static_configs:
      - targets: ["host.docker.internal:5000"]
    tls_config:
      insecure_skip_verify: true
