CREATE TABLE product (
    id INT AUTO_INCREMENT NOT NULL,
    brand VARCHAR(20) NOT NULL,
    name VARCHAR(20) NOT NULL,
    price INT NOT NULL,
    color VARCHAR(20) NOT NULL,
    system VARCHAR(10) NOT NULL,
    storage INT NOT NULL,
    short_desc TEXT NOT NULL,
    long_desc TEXT NOT NULL,
    image VARCHAR(30) NOT NULL,
    PRIMARY KEY (id)
);



CREATE TABLE user (
    id INT AUTO_INCREMENT NOT NULL,
    username VARCHAR(20) NOT NULL,
    password VARCHAR(30) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO user (username, password) VALUES ('admin', 'admin');

INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 8790, 'Purple', 'iOS', 64, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 8790kr, is in the lovely color of Purple. It runs on iOS and has 64GB of storage.', '1.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 7890, 'Purple', 'iOS', 64, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 7890kr, is in the lovely color of Purple. It runs on iOS and has 64GB of storage.', '2.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 8590, 'Purple', 'iOS', 128, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 8590kr, is in the lovely color of Purple. It runs on iOS and has 128GB of storage.', '3.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 9590, 'Purple', 'iOS', 128, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 9590kr, is in the lovely color of Purple. It runs on iOS and has 128GB of storage.', '4.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 9790, 'Purple', 'iOS', 256, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 9790kr, is in the lovely color of Purple. It runs on iOS and has 256GB of storage.', '5.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 10890, 'Purple', 'iOS', 256, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 10890kr, is in the lovely color of Purple. It runs on iOS and has 256GB of storage.', '6.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('OnePlus', '9', 7890, 'Black', 'Android', 128, 'The is the new 9 from OnePlus.', 'The 9 from OnePlus, which costs 7890kr, is in the lovely color of Black. It runs on Android and has 128GB of storage.', '7.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('OnePlus', '9', 7890, 'Blue', 'Android', 128, 'The is the new 9 from OnePlus.', 'The 9 from OnePlus, which costs 7890kr, is in the lovely color of Blue. It runs on Android and has 128GB of storage.', '8.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('OnePlus', '9', 8890, 'Purple', 'Android', 256, 'The is the new 9 from OnePlus.', 'The 9 from OnePlus, which costs 8890kr, is in the lovely color of Purple. It runs on Android and has 256GB of storage.', '9.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('OnePlus', '9', 8890, 'Black', 'Android', 256, 'The is the new 9 from OnePlus.', 'The 9 from OnePlus, which costs 8890kr, is in the lovely color of Black. It runs on Android and has 256GB of storage.', '10.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Motorola', 'Moto E7i Power', 1299, 'Blue', 'Android', 32, 'The is the new Moto E7i Power from Motorola.', 'The Moto E7i Power from Motorola, which costs 1299kr, is in the lovely color of Blue. It runs on Android and has 32GB of storage.', '11.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Motorola', 'Moto G100', 4999, 'White', 'Android', 128, 'The is the new Moto G100 from Motorola.', 'The Moto G100 from Motorola, which costs 4999kr, is in the lovely color of White. It runs on Android and has 128GB of storage.', '12.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Motorola', 'Moto G100', 4999, 'Blue', 'Android', 128, 'The is the new Moto G100 from Motorola.', 'The Moto G100 from Motorola, which costs 4999kr, is in the lovely color of Blue. It runs on Android and has 128GB of storage.', '13.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('OnePlus', '9 Pro', 9890, 'Black', 'Android', 128, 'The is the new 9 Pro from OnePlus.', 'The 9 Pro from OnePlus, which costs 9890kr, is in the lovely color of Black. It runs on Android and has 128GB of storage.', '14.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('OnePlus', '9 Pro', 9890, 'Silver', 'Android', 128, 'The is the new 9 Pro from OnePlus.', 'The 9 Pro from OnePlus, which costs 9890kr, is in the lovely color of Silver. It runs on Android and has 128GB of storage.', '15.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('OnePlus', '9 Pro', 9890, 'Green', 'Android', 128, 'The is the new 9 Pro from OnePlus.', 'The 9 Pro from OnePlus, which costs 9890kr, is in the lovely color of Green. It runs on Android and has 128GB of storage.', '16.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('OnePlus', '9 Pro', 10890, 'Black', 'Android', 256, 'The is the new 9 Pro from OnePlus.', 'The 9 Pro from OnePlus, which costs 10890kr, is in the lovely color of Black. It runs on Android and has 256GB of storage.', '17.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('OnePlus', '9 Pro', 10890, 'Green', 'Android', 256, 'The is the new 9 Pro from OnePlus.', 'The 9 Pro from OnePlus, which costs 10890kr, is in the lovely color of Green. It runs on Android and has 256GB of storage.', '18.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Xiaomi', 'Mi 11', 8690, 'Black', 'Android', 256, 'The is the new Mi 11 from Xiaomi.', 'The Mi 11 from Xiaomi, which costs 8690kr, is in the lovely color of Black. It runs on Android and has 256GB of storage.', '19.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Xiaomi', 'Mi 11', 8690, 'Blue', 'Android', 256, 'The is the new Mi 11 from Xiaomi.', 'The Mi 11 from Xiaomi, which costs 8690kr, is in the lovely color of Blue. It runs on Android and has 256GB of storage.', '20.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Motorola', 'Moto G30', 1999, 'White', 'Android', 128, 'The is the new Moto G30 from Motorola.', 'The Moto G30 from Motorola, which costs 1999kr, is in the lovely color of White. It runs on Android and has 128GB of storage.', '21.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Motorola', 'Moto G30', 1999, 'Black', 'Android', 128, 'The is the new Moto G30 from Motorola.', 'The Moto G30 from Motorola, which costs 1999kr, is in the lovely color of Black. It runs on Android and has 128GB of storage.', '22.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Motorola', 'Moto E6i', 999, 'Black', 'Android', 32, 'The is the new Moto E6i from Motorola.', 'The Moto E6i from Motorola, which costs 999kr, is in the lovely color of Black. It runs on Android and has 32GB of storage.', '23.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A52 4G', 3890, 'Black', 'Android', 128, 'The is the new Galaxy A52 4G from Samsung.', 'The Galaxy A52 4G from Samsung, which costs 3890kr, is in the lovely color of Black. It runs on Android and has 128GB of storage.', '24.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A52 4G', 3890, 'White', 'Android', 128, 'The is the new Galaxy A52 4G from Samsung.', 'The Galaxy A52 4G from Samsung, which costs 3890kr, is in the lovely color of White. It runs on Android and has 128GB of storage.', '25.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A52 4G', 3890, 'Purple', 'Android', 128, 'The is the new Galaxy A52 4G from Samsung.', 'The Galaxy A52 4G from Samsung, which costs 3890kr, is in the lovely color of Purple. It runs on Android and has 128GB of storage.', '26.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A52 4G', 3890, 'Blue', 'Android', 128, 'The is the new Galaxy A52 4G from Samsung.', 'The Galaxy A52 4G from Samsung, which costs 3890kr, is in the lovely color of Blue. It runs on Android and has 128GB of storage.', '27.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A52 5G', 4690, 'Black', 'Android', 128, 'The is the new Galaxy A52 5G from Samsung.', 'The Galaxy A52 5G from Samsung, which costs 4690kr, is in the lovely color of Black. It runs on Android and has 128GB of storage.', '28.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A52 5G', 4690, 'White', 'Android', 128, 'The is the new Galaxy A52 5G from Samsung.', 'The Galaxy A52 5G from Samsung, which costs 4690kr, is in the lovely color of White. It runs on Android and has 128GB of storage.', '29.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A52 5G', 4890, 'Black', 'Android', 128, 'The is the new Galaxy A52 5G from Samsung.', 'The Galaxy A52 5G from Samsung, which costs 4890kr, is in the lovely color of Black. It runs on Android and has 128GB of storage.', '30.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A72 4G', 4990, 'Blue', 'Android', 128, 'The is the new Galaxy A72 4G from Samsung.', 'The Galaxy A72 4G from Samsung, which costs 4990kr, is in the lovely color of Blue. It runs on Android and has 128GB of storage.', '31.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A72 4G', 4990, 'White', 'Android', 128, 'The is the new Galaxy A72 4G from Samsung.', 'The Galaxy A72 4G from Samsung, which costs 4990kr, is in the lovely color of White. It runs on Android and has 128GB of storage.', '32.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A72 4G', 4990, 'Black', 'Android', 128, 'The is the new Galaxy A72 4G from Samsung.', 'The Galaxy A72 4G from Samsung, which costs 4990kr, is in the lovely color of Black. It runs on Android and has 128GB of storage.', '33.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A52 5G', 4690, 'Blue', 'Android', 128, 'The is the new Galaxy A52 5G from Samsung.', 'The Galaxy A52 5G from Samsung, which costs 4690kr, is in the lovely color of Blue. It runs on Android and has 128GB of storage.', '34.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A52 5G', 4690, 'Purple', 'Android', 128, 'The is the new Galaxy A52 5G from Samsung.', 'The Galaxy A52 5G from Samsung, which costs 4690kr, is in the lovely color of Purple. It runs on Android and has 128GB of storage.', '35.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A72 4G', 4990, 'Purple', 'Android', 128, 'The is the new Galaxy A72 4G from Samsung.', 'The Galaxy A72 4G from Samsung, which costs 4990kr, is in the lovely color of Purple. It runs on Android and has 128GB of storage.', '36.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Asus', 'ROG Phone 5', 9999, 'Black', 'Android', 256, 'The is the new ROG Phone 5 from Asus.', 'The ROG Phone 5 from Asus, which costs 9999kr, is in the lovely color of Black. It runs on Android and has 256GB of storage.', '37.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Asus', 'ROG Phone 5', 10999, 'Black', 'Android', 256, 'The is the new ROG Phone 5 from Asus.', 'The ROG Phone 5 from Asus, which costs 10999kr, is in the lovely color of Black. It runs on Android and has 256GB of storage.', '38.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy XCover 5', 3290, 'Black', 'Android', 64, 'The is the new Galaxy XCover 5 from Samsung.', 'The Galaxy XCover 5 from Samsung, which costs 3290kr, is in the lovely color of Black. It runs on Android and has 64GB of storage.', '39.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A32 5G', 3090, 'Black', 'Android', 64, 'The is the new Galaxy A32 5G from Samsung.', 'The Galaxy A32 5G from Samsung, which costs 3090kr, is in the lovely color of Black. It runs on Android and has 64GB of storage.', '40.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A32 5G', 3090, 'Purple', 'Android', 64, 'The is the new Galaxy A32 5G from Samsung.', 'The Galaxy A32 5G from Samsung, which costs 3090kr, is in the lovely color of Purple. It runs on Android and has 64GB of storage.', '41.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A32 5G', 3090, 'White', 'Android', 64, 'The is the new Galaxy A32 5G from Samsung.', 'The Galaxy A32 5G from Samsung, which costs 3090kr, is in the lovely color of White. It runs on Android and has 64GB of storage.', '42.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A32 5G', 3090, 'Blue', 'Android', 64, 'The is the new Galaxy A32 5G from Samsung.', 'The Galaxy A32 5G from Samsung, which costs 3090kr, is in the lovely color of Blue. It runs on Android and has 64GB of storage.', '43.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Xiaomi', 'Redmi 9C NFC', 1290, 'Gray', 'Android', 64, 'The is the new Redmi 9C NFC from Xiaomi.', 'The Redmi 9C NFC from Xiaomi, which costs 1290kr, is in the lovely color of Gray. It runs on Android and has 64GB of storage.', '44.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21', 7990, 'Purple', 'Android', 128, 'The is the new Galaxy S21 from Samsung.', 'The Galaxy S21 from Samsung, which costs 7990kr, is in the lovely color of Purple. It runs on Android and has 128GB of storage.', '45.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21', 7990, 'White', 'Android', 128, 'The is the new Galaxy S21 from Samsung.', 'The Galaxy S21 from Samsung, which costs 7990kr, is in the lovely color of White. It runs on Android and has 128GB of storage.', '46.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21', 9790, 'Gray', 'Android', 128, 'The is the new Galaxy S21 from Samsung.', 'The Galaxy S21 from Samsung, which costs 9790kr, is in the lovely color of Gray. It runs on Android and has 128GB of storage.', '47.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21', 10490, 'Pink', 'Android', 256, 'The is the new Galaxy S21 from Samsung.', 'The Galaxy S21 from Samsung, which costs 10490kr, is in the lovely color of Pink. It runs on Android and has 256GB of storage.', '48.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21 Plus', 11990, 'Black', 'Android', 128, 'The is the new Galaxy S21 Plus from Samsung.', 'The Galaxy S21 Plus from Samsung, which costs 11990kr, is in the lovely color of Black. It runs on Android and has 128GB of storage.', '49.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21 Ultra', 11990, 'Silver', 'Android', 128, 'The is the new Galaxy S21 Ultra from Samsung.', 'The Galaxy S21 Ultra from Samsung, which costs 11990kr, is in the lovely color of Silver. It runs on Android and has 128GB of storage.', '50.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21 Ultra', 12490, 'Black', 'Android', 256, 'The is the new Galaxy S21 Ultra from Samsung.', 'The Galaxy S21 Ultra from Samsung, which costs 12490kr, is in the lovely color of Black. It runs on Android and has 256GB of storage.', '51.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21 Ultra', 16490, 'Silver', 'Android', 512, 'The is the new Galaxy S21 Ultra from Samsung.', 'The Galaxy S21 Ultra from Samsung, which costs 16490kr, is in the lovely color of Silver. It runs on Android and has 512GB of storage.', '52.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21', 7990, 'Pink', 'Android', 128, 'The is the new Galaxy S21 from Samsung.', 'The Galaxy S21 from Samsung, which costs 7990kr, is in the lovely color of Pink. It runs on Android and has 128GB of storage.', '53.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21', 7990, 'Gray', 'Android', 128, 'The is the new Galaxy S21 from Samsung.', 'The Galaxy S21 from Samsung, which costs 7990kr, is in the lovely color of Gray. It runs on Android and has 128GB of storage.', '54.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21', 10490, 'White', 'Android', 256, 'The is the new Galaxy S21 from Samsung.', 'The Galaxy S21 from Samsung, which costs 10490kr, is in the lovely color of White. It runs on Android and has 256GB of storage.', '55.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21', 10490, 'Purple', 'Android', 256, 'The is the new Galaxy S21 from Samsung.', 'The Galaxy S21 from Samsung, which costs 10490kr, is in the lovely color of Purple. It runs on Android and has 256GB of storage.', '56.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21', 10490, 'Gray', 'Android', 256, 'The is the new Galaxy S21 from Samsung.', 'The Galaxy S21 from Samsung, which costs 10490kr, is in the lovely color of Gray. It runs on Android and has 256GB of storage.', '57.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21 Plus', 11990, 'Silver', 'Android', 128, 'The is the new Galaxy S21 Plus from Samsung.', 'The Galaxy S21 Plus from Samsung, which costs 11990kr, is in the lovely color of Silver. It runs on Android and has 128GB of storage.', '58.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21 Ultra', 11990, 'Black', 'Android', 128, 'The is the new Galaxy S21 Ultra from Samsung.', 'The Galaxy S21 Ultra from Samsung, which costs 11990kr, is in the lovely color of Black. It runs on Android and has 128GB of storage.', '59.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21 Plus', 11990, 'Purple', 'Android', 128, 'The is the new Galaxy S21 Plus from Samsung.', 'The Galaxy S21 Plus from Samsung, which costs 11990kr, is in the lovely color of Purple. It runs on Android and has 128GB of storage.', '60.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21 Plus', 12790, 'Silver', 'Android', 256, 'The is the new Galaxy S21 Plus from Samsung.', 'The Galaxy S21 Plus from Samsung, which costs 12790kr, is in the lovely color of Silver. It runs on Android and has 256GB of storage.', '61.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21 Ultra', 16490, 'Black', 'Android', 512, 'The is the new Galaxy S21 Ultra from Samsung.', 'The Galaxy S21 Ultra from Samsung, which costs 16490kr, is in the lovely color of Black. It runs on Android and has 512GB of storage.', '62.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21 Ultra', 12490, 'Silver', 'Android', 256, 'The is the new Galaxy S21 Ultra from Samsung.', 'The Galaxy S21 Ultra from Samsung, which costs 12490kr, is in the lovely color of Silver. It runs on Android and has 256GB of storage.', '63.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21 Plus', 12790, 'Black', 'Android', 256, 'The is the new Galaxy S21 Plus from Samsung.', 'The Galaxy S21 Plus from Samsung, which costs 12790kr, is in the lovely color of Black. It runs on Android and has 256GB of storage.', '64.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S21 Plus', 12790, 'Purple', 'Android', 256, 'The is the new Galaxy S21 Plus from Samsung.', 'The Galaxy S21 Plus from Samsung, which costs 12790kr, is in the lovely color of Purple. It runs on Android and has 256GB of storage.', '65.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Nokia', '5.4', 2490, 'Blue', 'Android', 64, 'The is the new 5.4 from Nokia.', 'The 5.4 from Nokia, which costs 2490kr, is in the lovely color of Blue. It runs on Android and has 64GB of storage.', '66.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Nokia', '5.4', 2490, 'Purple', 'Android', 64, 'The is the new 5.4 from Nokia.', 'The 5.4 from Nokia, which costs 2490kr, is in the lovely color of Purple. It runs on Android and has 64GB of storage.', '67.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A02s', 1390, 'Black', 'Android', 32, 'The is the new Galaxy A02s from Samsung.', 'The Galaxy A02s from Samsung, which costs 1390kr, is in the lovely color of Black. It runs on Android and has 32GB of storage.', '68.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A02s', 1390, 'White', 'Android', 32, 'The is the new Galaxy A02s from Samsung.', 'The Galaxy A02s from Samsung, which costs 1390kr, is in the lovely color of White. It runs on Android and has 32GB of storage.', '69.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A12', 1990, 'White', 'Android', 64, 'The is the new Galaxy A12 from Samsung.', 'The Galaxy A12 from Samsung, which costs 1990kr, is in the lovely color of White. It runs on Android and has 64GB of storage.', '70.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A12', 1990, 'Black', 'Android', 64, 'The is the new Galaxy A12 from Samsung.', 'The Galaxy A12 from Samsung, which costs 1990kr, is in the lovely color of Black. It runs on Android and has 64GB of storage.', '71.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A12', 1990, 'Blue', 'Android', 64, 'The is the new Galaxy A12 from Samsung.', 'The Galaxy A12 from Samsung, which costs 1990kr, is in the lovely color of Blue. It runs on Android and has 64GB of storage.', '72.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Motorola', 'Moto E7', 1290, 'Red', 'Android', 32, 'The is the new Moto E7 from Motorola.', 'The Moto E7 from Motorola, which costs 1290kr, is in the lovely color of Red. It runs on Android and has 32GB of storage.', '73.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('OnePlus', 'Nord N10 5G', 2790, 'Blue', 'Android', 128, 'The is the new Nord N10 5G from OnePlus.', 'The Nord N10 5G from OnePlus, which costs 2790kr, is in the lovely color of Blue. It runs on Android and has 128GB of storage.', '74.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 7890, 'Black', 'iOS', 64, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 7890kr, is in the lovely color of Black. It runs on iOS and has 64GB of storage.', '75.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 7890, 'Red', 'iOS', 64, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 7890kr, is in the lovely color of Red. It runs on iOS and has 64GB of storage.', '76.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 8590, 'Blue', 'iOS', 128, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 8590kr, is in the lovely color of Blue. It runs on iOS and has 128GB of storage.', '77.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 8590, 'White', 'iOS', 128, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 8590kr, is in the lovely color of White. It runs on iOS and has 128GB of storage.', '78.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 8590, 'Red', 'iOS', 128, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 8590kr, is in the lovely color of Red. It runs on iOS and has 128GB of storage.', '79.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 9790, 'White', 'iOS', 256, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 9790kr, is in the lovely color of White. It runs on iOS and has 256GB of storage.', '80.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 9790, 'Green', 'iOS', 256, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 9790kr, is in the lovely color of Green. It runs on iOS and has 256GB of storage.', '81.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 9790, 'Black', 'iOS', 256, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 9790kr, is in the lovely color of Black. It runs on iOS and has 256GB of storage.', '82.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 9790, 'Blue', 'iOS', 256, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 9790kr, is in the lovely color of Blue. It runs on iOS and has 256GB of storage.', '83.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro Max', 13890, 'Gold', 'iOS', 128, 'The is the new iPhone 12 Pro Max from Apple.', 'The iPhone 12 Pro Max from Apple, which costs 13890kr, is in the lovely color of Gold. It runs on iOS and has 128GB of storage.', '84.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro Max', 14990, 'Gray', 'iOS', 256, 'The is the new iPhone 12 Pro Max from Apple.', 'The iPhone 12 Pro Max from Apple, which costs 14990kr, is in the lovely color of Gray. It runs on iOS and has 256GB of storage.', '85.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro Max', 14990, 'Gold', 'iOS', 256, 'The is the new iPhone 12 Pro Max from Apple.', 'The iPhone 12 Pro Max from Apple, which costs 14990kr, is in the lovely color of Gold. It runs on iOS and has 256GB of storage.', '86.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro Max', 17790, 'Gold', 'iOS', 512, 'The is the new iPhone 12 Pro Max from Apple.', 'The iPhone 12 Pro Max from Apple, which costs 17790kr, is in the lovely color of Gold. It runs on iOS and has 512GB of storage.', '87.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 7890, 'White', 'iOS', 64, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 7890kr, is in the lovely color of White. It runs on iOS and has 64GB of storage.', '88.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 7890, 'Green', 'iOS', 64, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 7890kr, is in the lovely color of Green. It runs on iOS and has 64GB of storage.', '89.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 7890, 'Blue', 'iOS', 64, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 7890kr, is in the lovely color of Blue. It runs on iOS and has 64GB of storage.', '90.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 8590, 'Green', 'iOS', 128, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 8590kr, is in the lovely color of Green. It runs on iOS and has 128GB of storage.', '91.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 8590, 'Black', 'iOS', 128, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 8590kr, is in the lovely color of Black. It runs on iOS and has 128GB of storage.', '92.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 mini', 9790, 'Red', 'iOS', 256, 'The is the new iPhone 12 mini from Apple.', 'The iPhone 12 mini from Apple, which costs 9790kr, is in the lovely color of Red. It runs on iOS and has 256GB of storage.', '93.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro Max', 13890, 'Blue', 'iOS', 128, 'The is the new iPhone 12 Pro Max from Apple.', 'The iPhone 12 Pro Max from Apple, which costs 13890kr, is in the lovely color of Blue. It runs on iOS and has 128GB of storage.', '94.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro Max', 13890, 'Silver', 'iOS', 128, 'The is the new iPhone 12 Pro Max from Apple.', 'The iPhone 12 Pro Max from Apple, which costs 13890kr, is in the lovely color of Silver. It runs on iOS and has 128GB of storage.', '95.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro Max', 13890, 'Gray', 'iOS', 128, 'The is the new iPhone 12 Pro Max from Apple.', 'The iPhone 12 Pro Max from Apple, which costs 13890kr, is in the lovely color of Gray. It runs on iOS and has 128GB of storage.', '96.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro Max', 14990, 'Silver', 'iOS', 256, 'The is the new iPhone 12 Pro Max from Apple.', 'The iPhone 12 Pro Max from Apple, which costs 14990kr, is in the lovely color of Silver. It runs on iOS and has 256GB of storage.', '97.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro Max', 14990, 'Blue', 'iOS', 256, 'The is the new iPhone 12 Pro Max from Apple.', 'The iPhone 12 Pro Max from Apple, which costs 14990kr, is in the lovely color of Blue. It runs on iOS and has 256GB of storage.', '98.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro Max', 17790, 'Blue', 'iOS', 512, 'The is the new iPhone 12 Pro Max from Apple.', 'The iPhone 12 Pro Max from Apple, which costs 17790kr, is in the lovely color of Blue. It runs on iOS and has 512GB of storage.', '99.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro Max', 17790, 'Silver', 'iOS', 512, 'The is the new iPhone 12 Pro Max from Apple.', 'The iPhone 12 Pro Max from Apple, which costs 17790kr, is in the lovely color of Silver. It runs on iOS and has 512GB of storage.', '100.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro Max', 17790, 'Gray', 'iOS', 512, 'The is the new iPhone 12 Pro Max from Apple.', 'The iPhone 12 Pro Max from Apple, which costs 17790kr, is in the lovely color of Gray. It runs on iOS and has 512GB of storage.', '101.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Motorola', 'Moto G9 Power', 1790, 'Green', 'Android', 128, 'The is the new Moto G9 Power from Motorola.', 'The Moto G9 Power from Motorola, which costs 1790kr, is in the lovely color of Green. It runs on Android and has 128GB of storage.', '102.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Motorola', 'Moto G9 Power', 1790, 'Purple', 'Android', 128, 'The is the new Moto G9 Power from Motorola.', 'The Moto G9 Power from Motorola, which costs 1790kr, is in the lovely color of Purple. It runs on Android and has 128GB of storage.', '103.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('OnePlus', 'Nord N100', 1111, 'Gray', 'Android', 64, 'The is the new Nord N100 from OnePlus.', 'The Nord N100 from OnePlus, which costs 1111kr, is in the lovely color of Gray. It runs on Android and has 64GB of storage.', '104.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Lenovo', 'Legion Phone Duel', 7990, 'Blue', 'Android', 512, 'The is the new Legion Phone Duel from Lenovo.', 'The Legion Phone Duel from Lenovo, which costs 7990kr, is in the lovely color of Blue. It runs on Android and has 512GB of storage.', '105.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Fairphone', '3 Plus', 5490, 'Black', 'Android', 64, 'The is the new 3 Plus from Fairphone.', 'The 3 Plus from Fairphone, which costs 5490kr, is in the lovely color of Black. It runs on Android and has 64GB of storage.', '106.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 11', 7990, 'White', 'iOS', 128, 'The is the new iPhone 11 from Apple.', 'The iPhone 11 from Apple, which costs 7990kr, is in the lovely color of White. It runs on iOS and has 128GB of storage.', '107.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 11', 7990, 'Black', 'iOS', 128, 'The is the new iPhone 11 from Apple.', 'The iPhone 11 from Apple, which costs 7990kr, is in the lovely color of Black. It runs on iOS and has 128GB of storage.', '108.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 11', 7490, 'Black', 'iOS', 64, 'The is the new iPhone 11 from Apple.', 'The iPhone 11 from Apple, which costs 7490kr, is in the lovely color of Black. It runs on iOS and has 64GB of storage.', '109.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 11', 7490, 'White', 'iOS', 64, 'The is the new iPhone 11 from Apple.', 'The iPhone 11 from Apple, which costs 7490kr, is in the lovely color of White. It runs on iOS and has 64GB of storage.', '110.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A42 5G', 2890, 'Gray', 'Android', 128, 'The is the new Galaxy A42 5G from Samsung.', 'The Galaxy A42 5G from Samsung, which costs 2890kr, is in the lovely color of Gray. It runs on Android and has 128GB of storage.', '111.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone SE', 4990, 'Black', 'iOS', 64, 'The is the new iPhone SE from Apple.', 'The iPhone SE from Apple, which costs 4990kr, is in the lovely color of Black. It runs on iOS and has 64GB of storage.', '112.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone SE', 5490, 'White', 'iOS', 128, 'The is the new iPhone SE from Apple.', 'The iPhone SE from Apple, which costs 5490kr, is in the lovely color of White. It runs on iOS and has 128GB of storage.', '113.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone SE', 5490, 'Red', 'iOS', 128, 'The is the new iPhone SE from Apple.', 'The iPhone SE from Apple, which costs 5490kr, is in the lovely color of Red. It runs on iOS and has 128GB of storage.', '114.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone SE', 5490, 'Black', 'iOS', 128, 'The is the new iPhone SE from Apple.', 'The iPhone SE from Apple, which costs 5490kr, is in the lovely color of Black. It runs on iOS and has 128GB of storage.', '115.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone SE', 6990, 'Red', 'iOS', 256, 'The is the new iPhone SE from Apple.', 'The iPhone SE from Apple, which costs 6990kr, is in the lovely color of Red. It runs on iOS and has 256GB of storage.', '116.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone SE', 6990, 'White', 'iOS', 256, 'The is the new iPhone SE from Apple.', 'The iPhone SE from Apple, which costs 6990kr, is in the lovely color of White. It runs on iOS and has 256GB of storage.', '117.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A42 5G', 2890, 'Black', 'Android', 128, 'The is the new Galaxy A42 5G from Samsung.', 'The Galaxy A42 5G from Samsung, which costs 2890kr, is in the lovely color of Black. It runs on Android and has 128GB of storage.', '118.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy A42 5G', 2890, 'White', 'Android', 128, 'The is the new Galaxy A42 5G from Samsung.', 'The Galaxy A42 5G from Samsung, which costs 2890kr, is in the lovely color of White. It runs on Android and has 128GB of storage.', '119.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone SE', 4990, 'Red', 'iOS', 64, 'The is the new iPhone SE from Apple.', 'The iPhone SE from Apple, which costs 4990kr, is in the lovely color of Red. It runs on iOS and has 64GB of storage.', '120.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone SE', 4990, 'White', 'iOS', 64, 'The is the new iPhone SE from Apple.', 'The iPhone SE from Apple, which costs 4990kr, is in the lovely color of White. It runs on iOS and has 64GB of storage.', '121.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone SE', 6990, 'Black', 'iOS', 256, 'The is the new iPhone SE from Apple.', 'The iPhone SE from Apple, which costs 6990kr, is in the lovely color of Black. It runs on iOS and has 256GB of storage.', '122.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone XR', 5990, 'Black', 'iOS', 64, 'The is the new iPhone XR from Apple.', 'The iPhone XR from Apple, which costs 5990kr, is in the lovely color of Black. It runs on iOS and has 64GB of storage.', '123.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone XR', 5990, 'White', 'iOS', 64, 'The is the new iPhone XR from Apple.', 'The iPhone XR from Apple, which costs 5990kr, is in the lovely color of White. It runs on iOS and has 64GB of storage.', '124.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 8790, 'Green', 'iOS', 64, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 8790kr, is in the lovely color of Green. It runs on iOS and has 64GB of storage.', '125.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 8790, 'Blue', 'iOS', 64, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 8790kr, is in the lovely color of Blue. It runs on iOS and has 64GB of storage.', '126.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 9590, 'Red', 'iOS', 128, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 9590kr, is in the lovely color of Red. It runs on iOS and has 128GB of storage.', '127.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 9590, 'Blue', 'iOS', 128, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 9590kr, is in the lovely color of Blue. It runs on iOS and has 128GB of storage.', '128.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 9590, 'Green', 'iOS', 128, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 9590kr, is in the lovely color of Green. It runs on iOS and has 128GB of storage.', '129.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 10890, 'White', 'iOS', 256, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 10890kr, is in the lovely color of White. It runs on iOS and has 256GB of storage.', '130.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 10890, 'Blue', 'iOS', 256, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 10890kr, is in the lovely color of Blue. It runs on iOS and has 256GB of storage.', '131.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 10890, 'Black', 'iOS', 256, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 10890kr, is in the lovely color of Black. It runs on iOS and has 256GB of storage.', '132.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 10890, 'Green', 'iOS', 256, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 10890kr, is in the lovely color of Green. It runs on iOS and has 256GB of storage.', '133.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro', 12990, 'Gray', 'iOS', 128, 'The is the new iPhone 12 Pro from Apple.', 'The iPhone 12 Pro from Apple, which costs 12990kr, is in the lovely color of Gray. It runs on iOS and has 128GB of storage.', '134.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro', 12990, 'Blue', 'iOS', 128, 'The is the new iPhone 12 Pro from Apple.', 'The iPhone 12 Pro from Apple, which costs 12990kr, is in the lovely color of Blue. It runs on iOS and has 128GB of storage.', '135.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro', 12990, 'Silver', 'iOS', 128, 'The is the new iPhone 12 Pro from Apple.', 'The iPhone 12 Pro from Apple, which costs 12990kr, is in the lovely color of Silver. It runs on iOS and has 128GB of storage.', '136.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro', 12990, 'Gold', 'iOS', 128, 'The is the new iPhone 12 Pro from Apple.', 'The iPhone 12 Pro from Apple, which costs 12990kr, is in the lovely color of Gold. It runs on iOS and has 128GB of storage.', '137.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro', 13990, 'Silver', 'iOS', 256, 'The is the new iPhone 12 Pro from Apple.', 'The iPhone 12 Pro from Apple, which costs 13990kr, is in the lovely color of Silver. It runs on iOS and has 256GB of storage.', '138.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro', 13990, 'Gold', 'iOS', 256, 'The is the new iPhone 12 Pro from Apple.', 'The iPhone 12 Pro from Apple, which costs 13990kr, is in the lovely color of Gold. It runs on iOS and has 256GB of storage.', '139.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro', 16490, 'Gold', 'iOS', 512, 'The is the new iPhone 12 Pro from Apple.', 'The iPhone 12 Pro from Apple, which costs 16490kr, is in the lovely color of Gold. It runs on iOS and has 512GB of storage.', '140.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Nokia', 'Nokia 3.4', 1790, 'Blue', 'Android', 32, 'The is the new Nokia 3.4 from Nokia.', 'The Nokia 3.4 from Nokia, which costs 1790kr, is in the lovely color of Blue. It runs on Android and has 32GB of storage.', '141.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Nokia', 'Nokia 3.4', 1790, 'Gray', 'Android', 32, 'The is the new Nokia 3.4 from Nokia.', 'The Nokia 3.4 from Nokia, which costs 1790kr, is in the lovely color of Gray. It runs on Android and has 32GB of storage.', '142.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Nokia', 'Nokia 3.4', 1790, 'Purple', 'Android', 32, 'The is the new Nokia 3.4 from Nokia.', 'The Nokia 3.4 from Nokia, which costs 1790kr, is in the lovely color of Purple. It runs on Android and has 32GB of storage.', '143.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 8790, 'Black', 'iOS', 64, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 8790kr, is in the lovely color of Black. It runs on iOS and has 64GB of storage.', '144.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 8790, 'White', 'iOS', 64, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 8790kr, is in the lovely color of White. It runs on iOS and has 64GB of storage.', '145.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 8790, 'Red', 'iOS', 64, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 8790kr, is in the lovely color of Red. It runs on iOS and has 64GB of storage.', '146.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 9590, 'Black', 'iOS', 128, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 9590kr, is in the lovely color of Black. It runs on iOS and has 128GB of storage.', '147.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 9590, 'White', 'iOS', 128, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 9590kr, is in the lovely color of White. It runs on iOS and has 128GB of storage.', '148.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12', 10890, 'Red', 'iOS', 256, 'The is the new iPhone 12 from Apple.', 'The iPhone 12 from Apple, which costs 10890kr, is in the lovely color of Red. It runs on iOS and has 256GB of storage.', '149.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro', 13990, 'Gray', 'iOS', 256, 'The is the new iPhone 12 Pro from Apple.', 'The iPhone 12 Pro from Apple, which costs 13990kr, is in the lovely color of Gray. It runs on iOS and has 256GB of storage.', '150.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro', 13990, 'Blue', 'iOS', 256, 'The is the new iPhone 12 Pro from Apple.', 'The iPhone 12 Pro from Apple, which costs 13990kr, is in the lovely color of Blue. It runs on iOS and has 256GB of storage.', '151.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro', 16490, 'Blue', 'iOS', 512, 'The is the new iPhone 12 Pro from Apple.', 'The iPhone 12 Pro from Apple, which costs 16490kr, is in the lovely color of Blue. It runs on iOS and has 512GB of storage.', '152.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro', 16490, 'Silver', 'iOS', 512, 'The is the new iPhone 12 Pro from Apple.', 'The iPhone 12 Pro from Apple, which costs 16490kr, is in the lovely color of Silver. It runs on iOS and has 512GB of storage.', '153.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Apple', 'iPhone 12 Pro', 16490, 'Gray', 'iOS', 512, 'The is the new iPhone 12 Pro from Apple.', 'The iPhone 12 Pro from Apple, which costs 16490kr, is in the lovely color of Gray. It runs on iOS and has 512GB of storage.', '154.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Motorola', 'Motorola Razr 5G', 15990, 'Black', 'Android', 256, 'The is the new Motorola Razr 5G from Motorola.', 'The Motorola Razr 5G from Motorola, which costs 15990kr, is in the lovely color of Black. It runs on Android and has 256GB of storage.', '155.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Xiaomi', 'Mi 10T', 5990, 'Black', 'Android', 128, 'The is the new Mi 10T from Xiaomi.', 'The Mi 10T from Xiaomi, which costs 5990kr, is in the lovely color of Black. It runs on Android and has 128GB of storage.', '156.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('OnePlus', '8T', 5555, 'Green', 'Android', 128, 'The is the new 8T from OnePlus.', 'The 8T from OnePlus, which costs 5555kr, is in the lovely color of Green. It runs on Android and has 128GB of storage.', '157.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('OnePlus', '8T', 5555, 'Silver', 'Android', 128, 'The is the new 8T from OnePlus.', 'The 8T from OnePlus, which costs 5555kr, is in the lovely color of Silver. It runs on Android and has 128GB of storage.', '158.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('OnePlus', '8T', 6490, 'Green', 'Android', 256, 'The is the new 8T from OnePlus.', 'The 8T from OnePlus, which costs 6490kr, is in the lovely color of Green. It runs on Android and has 256GB of storage.', '159.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Sony', 'Sony Xperia 5 II', 6499, 'Black', 'Android', 128, 'The is the new Sony Xperia 5 II from Sony.', 'The Sony Xperia 5 II from Sony, which costs 6499kr, is in the lovely color of Black. It runs on Android and has 128GB of storage.', '160.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Sony', 'Sony Xperia 5 II', 6499, 'Blue', 'Android', 128, 'The is the new Sony Xperia 5 II from Sony.', 'The Sony Xperia 5 II from Sony, which costs 6499kr, is in the lovely color of Blue. It runs on Android and has 128GB of storage.', '161.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Huawei', 'P Smart 2021', 2490, 'Gold', 'Android', 128, 'The is the new P Smart 2021 from Huawei.', 'The P Smart 2021 from Huawei, which costs 2490kr, is in the lovely color of Gold. It runs on Android and has 128GB of storage.', '162.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Huawei', 'P Smart 2021', 2490, 'Green', 'Android', 128, 'The is the new P Smart 2021 from Huawei.', 'The P Smart 2021 from Huawei, which costs 2490kr, is in the lovely color of Green. It runs on Android and has 128GB of storage.', '163.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Nokia', 'Nokia 2.4', 1490, 'Gray', 'Android', 32, 'The is the new Nokia 2.4 from Nokia.', 'The Nokia 2.4 from Nokia, which costs 1490kr, is in the lovely color of Gray. It runs on Android and has 32GB of storage.', '164.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Nokia', 'Nokia 2.4', 1490, 'Purple', 'Android', 32, 'The is the new Nokia 2.4 from Nokia.', 'The Nokia 2.4 from Nokia, which costs 1490kr, is in the lovely color of Purple. It runs on Android and has 32GB of storage.', '165.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Nokia', 'Nokia 2.4', 1490, 'Blue', 'Android', 32, 'The is the new Nokia 2.4 from Nokia.', 'The Nokia 2.4 from Nokia, which costs 1490kr, is in the lovely color of Blue. It runs on Android and has 32GB of storage.', '166.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 9190, 'Pink', 'Android', 256, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 9190kr, is in the lovely color of Pink. It runs on Android and has 256GB of storage.', '167.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 9190, 'Green', 'Android', 256, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 9190kr, is in the lovely color of Green. It runs on Android and has 256GB of storage.', '168.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 8190, 'Red', 'Android', 256, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 8190kr, is in the lovely color of Red. It runs on Android and has 256GB of storage.', '169.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 9190, 'Orange', 'Android', 256, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 9190kr, is in the lovely color of Orange. It runs on Android and has 256GB of storage.', '170.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 8190, 'Orange', 'Android', 256, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 8190kr, is in the lovely color of Orange. It runs on Android and has 256GB of storage.', '171.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 8190, 'Pink', 'Android', 256, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 8190kr, is in the lovely color of Pink. It runs on Android and has 256GB of storage.', '172.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 8190, 'Green', 'Android', 256, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 8190kr, is in the lovely color of Green. It runs on Android and has 256GB of storage.', '173.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 8190, 'White', 'Android', 256, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 8190kr, is in the lovely color of White. It runs on Android and has 256GB of storage.', '174.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 9190, 'Blue', 'Android', 256, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 9190kr, is in the lovely color of Blue. It runs on Android and has 256GB of storage.', '175.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 9190, 'White', 'Android', 256, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 9190kr, is in the lovely color of White. It runs on Android and has 256GB of storage.', '176.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 9190, 'Red', 'Android', 256, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 9190kr, is in the lovely color of Red. It runs on Android and has 256GB of storage.', '177.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('OnePlus', 'Nord', 5490, 'Gray', 'Android', 256, 'The is the new Nord from OnePlus.', 'The Nord from OnePlus, which costs 5490kr, is in the lovely color of Gray. It runs on Android and has 256GB of storage.', '178.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Nokia', 'Nokia 8.3', 4497, 'Blue', 'Android', 128, 'The is the new Nokia 8.3 from Nokia.', 'The Nokia 8.3 from Nokia, which costs 4497kr, is in the lovely color of Blue. It runs on Android and has 128GB of storage.', '179.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 7490, 'Pink', 'Android', 128, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 7490kr, is in the lovely color of Pink. It runs on Android and has 128GB of storage.', '180.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 7490, 'Green', 'Android', 128, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 7490kr, is in the lovely color of Green. It runs on Android and has 128GB of storage.', '181.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 7490, 'White', 'Android', 128, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 7490kr, is in the lovely color of White. It runs on Android and has 128GB of storage.', '182.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 7490, 'Orange', 'Android', 128, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 7490kr, is in the lovely color of Orange. It runs on Android and has 128GB of storage.', '183.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 7490, 'Red', 'Android', 128, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 7490kr, is in the lovely color of Red. It runs on Android and has 128GB of storage.', '184.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 8490, 'Blue', 'Android', 128, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 8490kr, is in the lovely color of Blue. It runs on Android and has 128GB of storage.', '185.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 8490, 'Red', 'Android', 128, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 8490kr, is in the lovely color of Red. It runs on Android and has 128GB of storage.', '186.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 8490, 'White', 'Android', 128, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 8490kr, is in the lovely color of White. It runs on Android and has 128GB of storage.', '187.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 8490, 'Green', 'Android', 128, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 8490kr, is in the lovely color of Green. It runs on Android and has 128GB of storage.', '188.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 8490, 'Pink', 'Android', 128, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 8490kr, is in the lovely color of Pink. It runs on Android and has 128GB of storage.', '189.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 8490, 'Orange', 'Android', 128, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 8490kr, is in the lovely color of Orange. It runs on Android and has 128GB of storage.', '190.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy S20 FE', 7490, 'Blue', 'Android', 128, 'The is the new Galaxy S20 FE from Samsung.', 'The Galaxy S20 FE from Samsung, which costs 7490kr, is in the lovely color of Blue. It runs on Android and has 128GB of storage.', '191.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy Z Fold2 5G', 14444, 'Black', 'Android', 256, 'The is the new Galaxy Z Fold2 5G from Samsung.', 'The Galaxy Z Fold2 5G from Samsung, which costs 14444kr, is in the lovely color of Black. It runs on Android and has 256GB of storage.', '192.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy Z Fold2 5G', 14444, 'Copper', 'Android', 256, 'The is the new Galaxy Z Fold2 5G from Samsung.', 'The Galaxy Z Fold2 5G from Samsung, which costs 14444kr, is in the lovely color of Copper. It runs on Android and has 256GB of storage.', '193.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Motorola', 'Moto G9 Play', 1297, 'Green', 'Android', 64, 'The is the new Moto G9 Play from Motorola.', 'The Moto G9 Play from Motorola, which costs 1297kr, is in the lovely color of Green. It runs on Android and has 64GB of storage.', '194.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy Z Flip 5G', 11111, 'Gray', 'Android', 256, 'The is the new Galaxy Z Flip 5G from Samsung.', 'The Galaxy Z Flip 5G from Samsung, which costs 11111kr, is in the lovely color of Gray. It runs on Android and has 256GB of storage.', '195.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy Z Flip 5G', 11111, 'Copper', 'Android', 256, 'The is the new Galaxy Z Flip 5G from Samsung.', 'The Galaxy Z Flip 5G from Samsung, which costs 11111kr, is in the lovely color of Copper. It runs on Android and has 256GB of storage.', '196.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy Note20', 10997, 'Gray', 'Android', 256, 'The is the new Galaxy Note20 from Samsung.', 'The Galaxy Note20 from Samsung, which costs 10997kr, is in the lovely color of Gray. It runs on Android and has 256GB of storage.', '197.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy Note20', 10997, 'Copper', 'Android', 256, 'The is the new Galaxy Note20 from Samsung.', 'The Galaxy Note20 from Samsung, which costs 10997kr, is in the lovely color of Copper. It runs on Android and has 256GB of storage.', '198.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy Note20', 11997, 'Green', 'Android', 256, 'The is the new Galaxy Note20 from Samsung.', 'The Galaxy Note20 from Samsung, which costs 11997kr, is in the lovely color of Green. It runs on Android and has 256GB of storage.', '199.png');
INSERT INTO product (brand, name, price, color, system, storage, short_desc, long_desc, image) VALUES ('Samsung', 'Galaxy Note20 Ultra', 12997, 'Black', 'Android', 256, 'The is the new Galaxy Note20 Ultra from Samsung.', 'The Galaxy Note20 Ultra from Samsung, which costs 12997kr, is in the lovely color of Black. It runs on Android and has 256GB of storage.', '200.png');
